/*
 * The MIT License
 *
 * Copyright (c) 2011 Andrius Bentkus
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

// This code is autogenerated, do not modify

using System;
using System.Runtime.InteropServices;

namespace LibGit2Sharp.Core
{
    unsafe internal class NativeMethods
    {
        private const string libgit2 = "git2.dll";


        [DllImport(libgit2)]
        public static extern void *git_blob_rawcontent(git_blob *blob);

        [DllImport(libgit2)]
        public static extern int git_blob_rawsize(git_blob *blob);

        [DllImport(libgit2)]
        public static extern int git_blob_create_fromfile(git_oid *oid, git_repository *repo, string path);

        [DllImport(libgit2)]
        public static extern int git_blob_create_frombuffer(git_oid *oid, git_repository *repo, byte[] buffer, uint len);

        [DllImport(libgit2)]
        public static extern git_oid *git_commit_id(git_commit *commit);

        [DllImport(libgit2)]
        public static extern sbyte *git_commit_message_short(git_commit *commit);

        [DllImport(libgit2)]
        public static extern sbyte *git_commit_message(git_commit *commit);

        [DllImport(libgit2)]
        public static extern long git_commit_time(git_commit *commit);

        [DllImport(libgit2)]
        public static extern int git_commit_time_offset(git_commit *commit);

        [DllImport(libgit2)]
        public static extern git_signature *git_commit_committer(git_commit *commit);

        [DllImport(libgit2)]
        public static extern git_signature *git_commit_author(git_commit *commit);

        [DllImport(libgit2)]
        public static extern int git_commit_tree(git_tree **tree_out, git_commit *commit);

        [DllImport(libgit2)]
        public static extern uint git_commit_parentcount(git_commit *commit);

        [DllImport(libgit2)]
        public static extern int git_commit_parent(git_commit **parent, git_commit *commit, uint n);

        [DllImport(libgit2)]
        public static extern int git_commit_create(git_oid *oid, git_repository *repo, string update_ref, git_signature *author, git_signature *committer, string message, git_oid *tree_oid, int parent_count, git_oid **parent_oids);

        [DllImport(libgit2)]
        public static extern int git_commit_create_o(git_oid *oid, git_repository *repo, string update_ref, git_signature *author, git_signature *committer, string message, git_tree *tree, int parent_count, git_commit **parents);

        [DllImport(libgit2)]
        public static extern int git_commit_create_ov(git_oid *oid, git_repository *repo, string update_ref, git_signature *author, git_signature *committer, string message, git_tree *tree, int parent_count);

        [DllImport(libgit2)]
        public static extern int git_commit_create_v(git_oid *oid, git_repository *repo, string update_ref, git_signature *author, git_signature *committer, string message, git_oid *tree_oid, int parent_count);

        [DllImport(libgit2)]
        public static extern void git_strarray_free(git_strarray *array);

        [DllImport(libgit2)]
        public static extern sbyte *git_strerror(int num);

        [DllImport(libgit2)]
        public static extern int git_index_open_bare(git_index **index, string index_path);

        [DllImport(libgit2)]
        public static extern int git_index_open_inrepo(git_index **index, git_repository *repo);

        [DllImport(libgit2)]
        public static extern void git_index_clear(git_index *index);

        [DllImport(libgit2)]
        public static extern void git_index_free(git_index *index);

        [DllImport(libgit2)]
        public static extern int git_index_read(git_index *index);

        [DllImport(libgit2)]
        public static extern int git_index_write(git_index *index);

        [DllImport(libgit2)]
        public static extern int git_index_find(git_index *index, string path);

        [DllImport(libgit2)]
        public static extern int git_index_add(git_index *index, string path, int stage);

        [DllImport(libgit2)]
        public static extern int git_index_remove(git_index *index, int position);

        [DllImport(libgit2)]
        public static extern int git_index_insert(git_index *index, git_index_entry *source_entry);

        [DllImport(libgit2)]
        public static extern git_index_entry *git_index_get(git_index *index, int n);

        [DllImport(libgit2)]
        public static extern uint git_index_entrycount(git_index *index);

        [DllImport(libgit2)]
        public static extern int git_object_lookup(git_object **obj, git_repository *repo, git_oid *id, git_otype type);

        [DllImport(libgit2)]
        public static extern git_oid *git_object_id(git_object *obj);

        [DllImport(libgit2)]
        public static extern git_otype git_object_type(git_object *obj);

        [DllImport(libgit2)]
        public static extern git_repository *git_object_owner(git_object *obj);

        [DllImport(libgit2)]
        public static extern void git_object_close(git_object *obj);

        [DllImport(libgit2)]
        public static extern sbyte *git_object_type2string(git_otype type);

        [DllImport(libgit2)]
        public static extern git_otype git_object_string2type(string str);

        [DllImport(libgit2)]
        public static extern int git_object_typeisloose(git_otype type);

        [DllImport(libgit2)]
        public static extern uint git_object__size(git_otype type);

        [DllImport(libgit2)]
        public static extern int git_odb_new(git_odb **outt);

        [DllImport(libgit2)]
        public static extern int git_odb_open(git_odb **outt, string objects_dir);

        [DllImport(libgit2)]
        public static extern int git_odb_add_backend(git_odb *odb, git_odb_backend *backend, int priority);

        [DllImport(libgit2)]
        public static extern int git_odb_add_alternate(git_odb *odb, git_odb_backend *backend, int priority);

        [DllImport(libgit2)]
        public static extern void git_odb_close(git_odb *db);

        [DllImport(libgit2)]
        public static extern int git_odb_read(git_odb_object **outt, git_odb *db, git_oid *id);

        [DllImport(libgit2)]
        public static extern int git_odb_read_header(out uint len_p, out git_otype type_p, git_odb *db, git_oid *id);

        [DllImport(libgit2)]
        public static extern int git_odb_exists(git_odb *db, git_oid *id);

        [DllImport(libgit2)]
        public static extern int git_odb_open_wstream(git_odb_stream **stream, git_odb *db, uint size, git_otype type);

        [DllImport(libgit2)]
        public static extern int git_odb_open_rstream(git_odb_stream **stream, git_odb *db, git_oid *oid);

        [DllImport(libgit2)]
        public static extern int git_odb_hash(git_oid *id, byte[] data, uint len, git_otype type);

        [DllImport(libgit2)]
        public static extern void git_odb_object_close(git_odb_object *obj);

        [DllImport(libgit2)]
        public static extern git_oid *git_odb_object_id(git_odb_object *obj);

        [DllImport(libgit2)]
        public static extern void *git_odb_object_data(git_odb_object *obj);

        [DllImport(libgit2)]
        public static extern uint git_odb_object_size(git_odb_object *obj);

        [DllImport(libgit2)]
        public static extern git_otype git_odb_object_type(git_odb_object *obj);

        [DllImport(libgit2)]
        public static extern int git_odb_backend_pack(git_odb_backend **backend_out, string objects_dir);

        [DllImport(libgit2)]
        public static extern int git_odb_backend_loose(git_odb_backend **backend_out, string objects_dir);

        [DllImport(libgit2)]
        public static extern int git_odb_backend_sqlite(git_odb_backend **backend_out, string sqlite_db);

        [DllImport(libgit2)]
        public static extern int git_oid_mkstr(git_oid *outt, string str);

        [DllImport(libgit2)]
        public static extern void git_oid_mkraw(git_oid *outt, string raw);

        [DllImport(libgit2)]
        public static extern void git_oid_fmt(sbyte *str, git_oid *oid);

        [DllImport(libgit2)]
        public static extern void git_oid_pathfmt(sbyte *str, git_oid *oid);

        [DllImport(libgit2)]
        public static extern string git_oid_allocfmt(git_oid *oid);

        [DllImport(libgit2)]
        public static extern string git_oid_to_string(sbyte *outt, uint n, git_oid *oid);

        [DllImport(libgit2)]
        public static extern void git_oid_cpy(git_oid *outt, git_oid *src);

        [DllImport(libgit2)]
        public static extern int git_oid_cmp(git_oid *a, git_oid *b);

        [DllImport(libgit2)]
        public static extern int git_reference_lookup(git_reference **reference_out, git_repository *repo, string name);

        [DllImport(libgit2)]
        public static extern int git_reference_create_symbolic(git_reference **ref_out, git_repository *repo, string name, string target);

        [DllImport(libgit2)]
        public static extern int git_reference_create_oid(git_reference **ref_out, git_repository *repo, string name, git_oid *id);

        [DllImport(libgit2)]
        public static extern git_oid *git_reference_oid(git_reference *reference);

        [DllImport(libgit2)]
        public static extern sbyte *git_reference_target(git_reference *reference);

        [DllImport(libgit2)]
        public static extern git_rtype git_reference_type(git_reference *reference);

        [DllImport(libgit2)]
        public static extern sbyte *git_reference_name(git_reference *reference);

        [DllImport(libgit2)]
        public static extern int git_reference_resolve(git_reference **resolved_ref, git_reference *reference);

        [DllImport(libgit2)]
        public static extern git_repository *git_reference_owner(git_reference *reference);

        [DllImport(libgit2)]
        public static extern int git_reference_set_target(git_reference *reference, string target);

        [DllImport(libgit2)]
        public static extern int git_reference_set_oid(git_reference *reference, git_oid *id);

        [DllImport(libgit2)]
        public static extern int git_reference_rename(git_reference *reference, string new_name);

        [DllImport(libgit2)]
        public static extern int git_reference_delete(git_reference *reference);

        [DllImport(libgit2)]
        public static extern int git_reference_packall(git_repository *repo);

        [DllImport(libgit2)]
        public static extern int git_reference_listall(git_strarray *array, git_repository *repo, uint list_flags);

        [DllImport(libgit2)]
        public static extern int git_repository_open(git_repository **repository, string path);

        [DllImport(libgit2)]
        public static extern int git_repository_open2(git_repository **repository, string git_dir, string git_object_directory, string git_index_file, string git_work_tree);

        [DllImport(libgit2)]
        public static extern int git_repository_open3(git_repository **repository, string git_dir, git_odb *object_database, string git_index_file, string git_work_tree);

        [DllImport(libgit2)]
        public static extern git_odb *git_repository_database(git_repository *repo);

        [DllImport(libgit2)]
        public static extern int git_repository_index(git_index **index, git_repository *repo);

        [DllImport(libgit2)]
        public static extern void git_repository_free(git_repository *repo);

        [DllImport(libgit2)]
        public static extern int git_repository_gc(git_repository *repo);

        [DllImport(libgit2)]
        public static extern int git_repository_init(git_repository **repo_out, string path, uint is_bare);

        [DllImport(libgit2)]
        public static extern int git_revwalk_new(git_revwalk **walker, git_repository *repo);

        [DllImport(libgit2)]
        public static extern void git_revwalk_reset(git_revwalk *walker);

        [DllImport(libgit2)]
        public static extern int git_revwalk_push(git_revwalk *walk, git_oid *oid);

        [DllImport(libgit2)]
        public static extern int git_revwalk_hide(git_revwalk *walk, git_oid *oid);

        [DllImport(libgit2)]
        public static extern int git_revwalk_next(git_oid *oid, git_revwalk *walk);

        [DllImport(libgit2)]
        public static extern void git_revwalk_sorting(git_revwalk *walk, uint sort_mode);

        [DllImport(libgit2)]
        public static extern void git_revwalk_free(git_revwalk *walk);

        [DllImport(libgit2)]
        public static extern git_repository *git_revwalk_repository(git_revwalk *walk);

        [DllImport(libgit2)]
        public static extern git_signature *git_signature_new(string name, string email, long time, int offset);

        [DllImport(libgit2)]
        public static extern git_signature *git_signature_dup(git_signature *sig);

        [DllImport(libgit2)]
        public static extern void git_signature_free(git_signature *sig);

        [DllImport(libgit2)]
        public static extern git_oid *git_tag_id(git_tag *tag);

        [DllImport(libgit2)]
        public static extern int git_tag_target(git_object **target, git_tag *t);

        [DllImport(libgit2)]
        public static extern git_oid *git_tag_target_oid(git_tag *t);

        [DllImport(libgit2)]
        public static extern git_otype git_tag_type(git_tag *t);

        [DllImport(libgit2)]
        public static extern sbyte *git_tag_name(git_tag *t);

        [DllImport(libgit2)]
        public static extern git_signature *git_tag_tagger(git_tag *t);

        [DllImport(libgit2)]
        public static extern sbyte *git_tag_message(git_tag *t);

        [DllImport(libgit2)]
        public static extern int git_tag_create(git_oid *oid, git_repository *repo, string tag_name, git_oid *target, git_otype target_type, git_signature *tagger, string message);

        [DllImport(libgit2)]
        public static extern int git_tag_create_o(git_oid *oid, git_repository *repo, string tag_name, git_object *target, git_signature *tagger, string message);

        [DllImport(libgit2)]
        public static extern git_oid *git_tree_id(git_tree *tree);

        [DllImport(libgit2)]
        public static extern uint git_tree_entrycount(git_tree *tree);

        [DllImport(libgit2)]
        public static extern git_tree_entry *git_tree_entry_byname(git_tree *tree, string filename);

        [DllImport(libgit2)]
        public static extern git_tree_entry *git_tree_entry_byindex(git_tree *tree, int idx);

        [DllImport(libgit2)]
        public static extern uint git_tree_entry_attributes(git_tree_entry *entry);

        [DllImport(libgit2)]
        public static extern sbyte *git_tree_entry_name(git_tree_entry *entry);

        [DllImport(libgit2)]
        public static extern git_oid *git_tree_entry_id(git_tree_entry *entry);

        [DllImport(libgit2)]
        public static extern int git_tree_entry_2object(git_object **object_out, git_repository *repo, git_tree_entry *entry);
    }
}
