using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace LibGit2Sharp
{
    /// <summary>
    /// Information about a rebase step that was just completed.
    /// </summary>
    public class AfterRebaseStepInfo
    {
        internal AfterRebaseStepInfo(RebaseStepInfo stepInfo, ObjectId commitId)
        {
            StepInfo = stepInfo;
            CommitId = commitId;
        }

        /// <summary>
        /// The info on the completed step.
        /// </summary>
        public RebaseStepInfo StepInfo { get; private set; }

        /// <summary>
        /// The ID of the commit generated by the step, if any.
        /// </summary>
        public ObjectId CommitId { get; private set; }
    }
}
