parameters:
  initArgs:

steps:

- powershell: |
    .\init.ps1 -AccessToken '$(System.AccessToken)' ${{ parameters['initArgs'] }} -UpgradePrerequisites
    dotnet --info
  displayName: Install prerequisites
